component-event-stream/cfn.yaml

This api does have an OPTIONS endpoint which works correctly, but the POST endpoint needs to include the `Access-Control-Allow-Origin` header.
I've also made the origin more specific in PROD.

Fix api cors

---

sql/create-aggregated-epic-views-table.sql

The partition assumes folder names in s3 have format `dt=2021-04-12-13-00/`.
Athena looks for data in:
`s3://gu-support-analytics/aggregated-epic-views/<STAGE>/`
E.g. of a file:
`s3://gu-support-analytics/aggregated-epic-views/PROD/dt=2021-04-12-13-00/<some_unique_name>.json`
Assumes files contain json data with e.g.:
```
{"url": "https...", "views": 20}
{"url": "https...", "views": 30}
```
For details of partitioning see https://docs.aws.amazon.com/athena/latest/ug/partitions.html

sql for aggregated-epic-views table

---

component-event-stream/cfn.yaml

Adds request body validation for epic view events. Request is deemed valid if both `url` and `countryCode` keys present and their values are strings.

update cloudformation for api gateway request validation

---

component-event-stream/cfn.yaml

We have a kinesis stream for epic view events.
This PR adds an alarm to detect when impressions drop below 20,000 in an hour.
We can also add streams for monitoring other channels, e.g. the banner. But doing this for the epic is a quick win as we're already collecting these events.

Alarm for minimum epic views

---

super-mode-calculator/package.json
super-mode-calculator/yarn.lock

Reverting the change as it caused TeamCity build failure

Revert "Bump typescript from 4.3.5 to 4.9.5 in /super-mode-calculator"

---

.github/workflows/component-event-stream.yaml
component-event-stream/scripts/riff_raff_upload.sh
super-mode-calculator/yarn.lock

Migrate [component-event-stream](https://github.com/guardian/support-analytics/tree/main/component-event-stream) from TeamCity to Github Actions.
DevX is planning to retire TeamCity by the end of September 2023. All workflows will need to be migrated to Github Actions
The TeamCity agent count will be continually decreasing from June onwards, reaching 0 by the end of September. So the build queues and therefore the time it takes to be able to deploy might increase, if the job count does not decrease.
‌
You should not use TeamCity for any new applications from now on.
Our main build service is now GitHub Actions. [GitHub Actions documentation - GitHub Docs](https://docs.github.com/en/actions) 
We will all benefit from this move by being able to keep our CI builds as code, version controlled …

Migrate the component-event-stream to GHA

---

super-mode-calculator/cfn-dynamodb.yaml

This PR allows us to start backing up the super-mode DynamoDB table using https://github.com/guardian/aws-backup. For more details on this project see [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit) and this [audit](https://docs.google.com/spreadsheets/d/1gNh_yQ3GVo_dVAemgZfRZM_MaQxep6_x-hzrhvVBGHY/edit#gid=1523470588) that @guardian/devx-reliability have been working on with Heads of Engineering.
I should be able to test this by deploying to `CODE` (see `Deployment` section below).
I will double check that backups are taken as expected after merging (this should happen the night after this PR is merged).
We will be able to recover (most) data stored in this table in the unlikely event that it is deleted.
Yes, a number of risks related to …

Enable nightly backups for the super-mode table

---

bandit/package.json
bandit/src/calculate-lambda/calculate-lambda.ts
bandit/src/calculate-lambda/dynamo.ts
bandit/src/calculate-lambda/parse.ts
bandit/src/query-lambda/local.ts
cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

Creates the main body of the calculate lambda to write the results of the query lambda (previous function in state machine) to dynamo. At the moment it's not actually calculating anything...
Run `AthenaOutputBucket=gu-support-analytics AWS_PROFILE=membership yarn local` - see results in dynamo table

Bandit Calculate Lambda - write results of query lambda to dynamo

---

bandit/src/calculate-lambda/dynamo.ts
cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

After discussions we decided that the `support-bandit-` dynamo table should be algorithm agnostic and just record the latest AV / view data for each test, not for each test + algorithm. This means the partition key will be `testName` instead of `testNameWithAlgorithm` and requires a recreation of the stack and table
Deploy to code, stack should recreate with dynamo table with new partition key.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast) …

Bandit Dynamo - change partition key to `testName`

---

bandit/src/calculate-lambda/calculate-lambda.ts
bandit/src/calculate-lambda/dynamo.ts
bandit/src/lib/models.ts
bandit/src/query-lambda/queries.ts
bandit/src/query-lambda/query-lambda.ts

Adds the start time of the interval being queried to the dynamo table `support-bandit-` to accurately show what the beginning of that time period was. In #326 we added precise intervals for the query, of duration one hour starting on the hour.
Before
After

Bandit - return the start time from query lambda and write in calculate lambda

---

bandit/src/calculate-lambda/dynamo.ts
bandit/src/calculate-lambda/parse.ts
bandit/src/query-lambda/queries.ts

Record each variant's views in the `support-bandit-` table, as this is the sample size of the AV/view so we need it if we want to calculate the overall mean.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

Bandit - record views per variant

---

bandit/src/query-lambda/queries.ts

It's possible for a variant to have some views but no acquisitions data. In this case we should default the acquisitions to 0 rather than null

Bandit: handle no acquisitions

---

bandit/src/calculate-lambda/calculate-lambda.ts
bandit/src/get-bandit-tests/get-bandit-tests.ts
bandit/src/query-lambda/local.ts
bandit/src/query-lambda/query-lambda.ts
bandit/src/scripts/backfill.ts

If there are no batches to write then it fails with:
`"errorMessage": "1 validation error detected: Value '{support-bandit-CODE=[]}' at 'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]",`
The query lambda takes a Date as the second parameter. This was introduced for the local backfill script, but actually broke the lambda in AWS because the second parameter will be some stuff that AWS passes in.

Bandit: fix lambdas

---

cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

Add a rule to schedule the state machine every hour on the hour
Deploy to CODE, check that the state machine kicks off on the hour

Bandit state machine - add scheduling rule

---

bandit/src/query-lambda/queries.ts

Update query to exclude high-value acquisitions from the Bandit algorithm by capping Annualised Value at £250 per acquisition so that the data is more optimised in order to derive information from.
We plucked out the acquisitions subquery from the query, amended it so that it included the if statement and used a value of 40 instead of 250:
```
SELECT
annualisedvaluegbp av_gbp,
IF(annualisedvaluegbp >= 40, 40, annualisedvaluegbp) capped_av_gbp
FROM acquisition.acquisition_events_prod, UNNEST(abtests) t(ab)
WHERE acquisition_date >= date'2024-04-17'
AND timestamp >= timestamp'2024-04-17 07:00:00' AND timestamp < timestamp'2024-04-25 07:00:00'
AND ab.name = '2024-02-09_MEGA_TOP_READER_EPIC__US'
```
We then ran it in Athena and verified that values over 40 were set to 40, and values of 40 and …

Bandit: cap annualised value at £250

---

bandit/src/query-lambda/bigquery.ts
bandit/src/query-lambda/build-query.ts
bandit/src/query-lambda/query-lambda.ts

The bandit query gets views + acquisitions for a specific 1-hour window.
This PR makes some changes:
1. uses `fact_page_view_anonymised`, as we should avoid using `fact_page_view`
2. adds a filter on event_timestamp for the specified hour - currently the query gets all `VIEW` events for the day
3. changes the query window to the hour _before_ last. This is because component_events can arrive in the pageview table a bit later, though the event_timestamp will be correct. So we get a more complete picture if we delay by an hour
E.g. log from running in CODE:

Use anonymised pageviews and filter on timestamp

---

bandit/src/get-bandit-tests/dynamo.ts
bandit/src/get-bandit-tests/get-bandit-tests.ts
bandit/src/lib/models.ts

We're migrating to a new way of modelling bandit tests: https://github.com/guardian/support-admin-console/pull/640/files#diff-805e9a8dadac4c5cc4074591de0677066ad2562f7455fa761b76db91e66f20fdR40
The `isBanditTest` field is being removed.
With this change we now fetch all live channel tests, and filter for bandit tests using the `methodologies` field.
This is because Dynamodb's filter expressions do not support the type of filtering we need here.

Use methodologies field in bandit

---

bandit/src/query-lambda/dynamo.ts

In the bandit data table we prefix the test name with the channel name, e.g.
`Epic_my-test`
This is because this field is the partition key and we want to avoid potential name clashes between epics + banners.
Currently there are spaces in the string, which isn't right

Remove spaces from bandit test name

---

bandit/src/query-lambda/bigquery.ts
bandit/src/query-lambda/query-lambda.ts

Currently it uses the current time, but we should be using `start`, which is current time minus 2 hours.
I've also removed some date logic from `getDataForBanditTest`. We now just pass in the start time, and it queries for 1 hour of data from then.

Use correct date in bandit

---

cdk/lib/__snapshots__/super-mode-calculator.test.ts.snap
cdk/lib/super-mode-calculator.ts
super-mode-calculator/package.json
super-mode-calculator/src/lambdas/calculate/parse.ts
super-mode-calculator/src/lambdas/lambda.ts
super-mode-calculator/src/lambdas/query/queries.ts
super-mode-calculator/src/lambdas/query/regionSql.ts
super-mode-calculator/src/lib/bigquery.ts
super-mode-calculator/src/lib/build-query.ts
super-mode-calculator/src/lib/dynamoV2.ts
super-mode-calculator/src/lib/ssm.ts
super-mode-calculator/yarn.lock

Super Mode currently uses Athena to query for impressions and annualised value. But all the required data for Super Mode  is available in BigQuery tables.So we can use BigQuery.Also in this PR, we are implementing a simple annualised value calculator with hard coded values for Supporter Plus which was missing previously in the Super mode data .
To get the
views related data - we use the online_traffic.fact_page_view_anonymised(for Page view data)
acquisitions related data - we use the datalake.fact_acquisition_event table (for live contributions data)
and for currency conversion rates we use the datalake.fixer_exchange_rates table (to convert to £)
This PR is to replace the existing  state machine with single lambda and us it to query the BigQuery tables for super mode .
Existing state …

Read from bigquery for super -mode- calculator

---

cdk/lib/__snapshots__/super-mode-calculator.test.ts.snap
cdk/lib/super-mode-calculator.ts

The new lambda for Super mode querying BigQuery has no AWS::Events::Rule added in the cloudformation .Hence it has no triggers.This is to fix that
Tested in CODE
support-super-mode-CODE-SuperModeCalculatorSuperMod-yZlV05XBs8a2  Rule was created in [Amazon EventBridge](https://eu-west-1.console.aws.amazon.com/events/home?region=eu-west-1#)

Fix the schedule for the super mode lambda

---

bandit/src/query-lambda/build-query.ts

We're currently missing annual acquisitions because the string should be `ANNUALLY`

Fix annual frequency in bandit query

---

super-mode-calculator/src/lib/bigquery.ts
super-mode-calculator/src/lib/build-query.ts

This is to update the super mode calculator query  to filter out epic views and correct the url used 
Tested for the url 'https://www.theguardian.com/world/2024/nov/22/russian-ballistic-missile-attack-ukraine-a-severe-escalation-says-zelenskyy'
WHERE event_timestamp >=timestamp '2024-11-22 07:00:00.000' AND event_timestamp <  timestamp '2024-11-22 09:00:00.000'

Update Super mode query for epic views

---

bandit/src/get-bandit-tests/get-bandit-tests.ts
bandit/src/lib/models.ts
bandit/src/query-lambda/query-lambda.ts

This PR has changes to filter out tests marked with Roulette selection method as bandit tests and thus populate the relevant bandit data for the Roulette tests

Add Roulette to the bandit system

---

cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

Co-authored by : @charleycampbell 
We recently discovered a bug in the Bandit data caused by duplicate test names being copied within the RRCP. This issue will be fixed as part of [this PR](https://github.com/guardian/support-admin-console/pull/670).
This PR introduces failure and timeout alarms for Bandit data. If either alarm is triggered, the Growth team will be notified in their alarms channel (which is[ configured here](https://github.com/guardian/support-service-lambdas/pull/2631))..
Testing
To verify these changes, we:
Built the new snapshot and deployed it to the code environment.
Triggered the Lambda step function to build, which failed due to duplicate test names (see first screenshot).
Confirmed that the alarm successfully notified the Growth team in their alarms channel (see …

Add alarms for bandit step function

---

super-mode-calculator/src/lib/build-query.ts
super-mode-calculator/src/parse.ts

Adds the total acquisitions count to the super mode dynamodb table.
It would be useful to show this in the super mode dashboard.

Add totalAcquisitions to super-mode data

---

cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

We've seen the bandit data state machine fail when the query lambda times out. This is presumably because of an issue connecting to BigQuery.
This PR updates the state machine to retry this lambda 5 times. The state machine runs hourly, so it's not urgent that it succeeds quickly.
Tested in CODE by:
1. deploying the branch to CODE
2. manually changing the lambda timeout to 2 seconds (too short)
3. starting a new state machine execution and waiting for it to fail a couple of times
4. manually changing the lambda timeout back to 1 minute
5. waiting for it to succeed

Retry bandit query lambda

---

cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

This system originally used Athena + S3 for its data.
But it now uses BigQuery.
This PR removes some old permissions that are no longer needed since the BigQuery migration

Remove athena permissions

---

cdk/lib/__snapshots__/bandit.test.ts.snap
cdk/lib/bandit.ts

The support-bandit state machine runs hourly to produce samples for the multi-armed bandit algorithms in SDC.
It queries the hourly pageview data in BigQuery.
Currently it runs at 15mins past the hour, every hour. It queries the hour before last, because we expect most of the component_event data for that hour to be ready by then.
In general this works fine, but we've noticed that the 01:15 run (which queries 23:00-00:00) is getting no data back from BigQuery.
E.g. -
Data Design have checked and told us:
"looks like the 23:00 - 23:59 run just takes ~2.5x as long as the usual hourly job."
They say it's always ready by 45mins past.
So this PR changes the schedule to run at 45 mins past the hour.

Change bandit schedule to 45mins past
